### PR TITLE
Update

### PR DESCRIPTION
**Pull request by microwavekonijn**
- Improvement to !ps2dig command(also auto-assigns role based on username);
- Role assignment on reaction;
- Temporary voice channels now can be configured to be inside a category;
- Possible fix for the anti-mention spam system not resetting.

### CODE REVIEW

**Review by Maelstromeous — APPROVED** [review]

**Review by Maelstromeous — CHANGES_REQUESTED** [review]
See screenshot

**Comment by microwavekonijn** [comment]
I saw was working on it. Instead of the lock, what do you propose. I use it know as a general indicator that the command needs special permission or in this case you are a guest so you are excluded from using it.

**Comment by Maelstromeous** [comment]
> I saw was working on it. Instead of the lock, what do you propose. I use it know as a general indicator that the command needs special permission or in this case you are a guest so you are excluded from using it.

Was thinking just a reply to the message?

**Comment by microwavekonijn** [comment]
I am not sure what to put there, as I don't want people to be directly aware that people with some roles are excluded.

**Comment by Maelstromeous** [comment]
> I am not sure what to put there, as I don't want people to be directly aware that people with some roles are excluded.

Can you give me more context of what's happening with it? Sorry I didn't have that much time to go into it in massive detail

**Comment by microwavekonijn** [comment]
Basically you can configure a array of roles(for guests for instance) that cannot use the command and thus claim a ps2 character to get the outfit role as a result.

**Comment by Maelstromeous** [comment]
> Basically you can configure a array of roles(for guests for instance) that cannot use the command and thus claim a ps2 character to get the outfit role as a result.

Ahh ok, maybe use a cross instead of a lockpad?

**Comment by microwavekonijn** [comment]
I tried the cross before, but I think I got the wrong symbol/emoji and it didn't work(even though I copied it from Discord). Now I use in general the lock to indicate that it needs special permission and red octagon(stop sign) to indicate that the command is throttled.

**Comment by Maelstromeous** [comment]
> I tried the cross before, but I think I got the wrong symbol/emoji and it didn't work(even though I copied it from Discord). Now I use in general the lock to indicate that it needs special permission and red octagon(stop sign) to indicate that the command is throttled.

Alright, if it's convention I'll let it slide :)

**Review by Maelstromeous — DISMISSED** [review]

**Comment by Maelstromeous** [comment]
Needs conflicts sorting :)

**Comment by microwavekonijn** [comment]
I am going to give it a test run, and then I will merge it.

**Comment by microwavekonijn** [comment]
Perfect, trying to test it. Is the api down -_-

**Pull request merged**
