### PR TITLE
#5 Style update with CI

### PR DESCRIPTION
**Pull request by JamesLongman**

### CODE REVIEW

**Comment by microwavekonijn** [comment]
I just checked and quotes, linebreak-style, semi, import/no-extraneous-dependencies, and no-console are the same or simplified when you compare it to the airbnb-base which we extend. I would remove them. Also we should eventually remove the no-use-before-define rule, airbnb only throws an error when a variable is used before it is declared(so strict mode)(functions, classes are exempted from this).

**Comment by microwavekonijn** [comment]
Btw, when this is merged, will the bot be in the same or better shape than the bot that is currently deployed? If we disable things like events(so broken parts which crash the bot), then we can finally push it to production so that Maelstromeous can finally retire his setup(as he wanted to retire his jenkins server).

**Comment by JamesLongman** [comment]
Well after this is should be in theory more stable as we’ve fixed a couple things already. But we’ve refactored nearly every line in our library so we should probably try to have a full QA run through on staging when it’s up

**Comment by microwavekonijn** [comment]
Any update? Is there something I could help with?

**Pull request merged**
